env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

name: Build and deploy ${{ env.REPOSITORY_NAME }}

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: 'v0.0.0'
        description: Release tag
        required: true
      environment:
        type: string
        default: 'Production'
        description: Environment
        required: true

jobs:
  build:
    name: Build ${{ env.REPOSITORY_NAME }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache .NET packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --verbosity normal

      - run: tree .

      - name: Publish linux-x64
        run: dotnet publish -c Release -r linux-x64 -p:PublishDir=C:\${{ env.REPOSITORY_NAME }}\linux-x64\${{ env.REPOSITORY_NAME }}-${{ inputs.tag }}

      - name: Publish win-x64
        run: dotnet publish -c Release -r win-x64 -p:PublishDir=C:\${{ env.REPOSITORY_NAME }}\win-x64\${{ env.REPOSITORY_NAME }}-${{ inputs.tag }}

      - name: Publish osx-x64
        run: dotnet publish -c Release -r osx-x64 -p:PublishDir=C:\${{ env.REPOSITORY_NAME }}\osx-x64\${{ env.REPOSITORY_NAME }}-${{ inputs.tag }}

      - name: Upload a Build Artifacts for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: C:/${{ env.REPOSITORY_NAME }}
          retention-days: 1

  deploy:
    name: Deploy ${{ env.REPOSITORY_NAME }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Download a Build Artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: artifact

      - run: tree .
      
      - name: Grant permission to OSX and Linux executables and zip all releases
        run: for i in */; do cd $i; [[ -f ${{ env.REPOSITORY_NAME }}-${{ inputs.tag }}/${{ env.REPOSITORY_NAME }} ]] && sudo chmod 777 ${{ env.REPOSITORY_NAME }}-${{ inputs.tag }}/${{ env.REPOSITORY_NAME }}; zip -r "../${{ env.REPOSITORY_NAME }}-${{ inputs.tag }}_${i%/}.zip" "."; cd ..; done

      - run: tree .

      - name: Release ${{ env.REPOSITORY_NAME }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *win-x64*.zip
            *linux-x64*.zip
            *osx-x64*.zip
          tag_name: ${{ inputs.tag }}
