name: Build and deploy BioParallel
run-name: Build and deploy ${{ github.event.repository.name }}-${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: 'v0.0.0'
        description: Release tag
        required: true
      environment:
        type: string
        default: 'Production'
        description: Environment
        required: true

jobs:
  build:
    name: Build ${{ github.event.repository.name }}-${{ inputs.tag }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: echo ${{ github.workspace }}

      - name: Cache .NET packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.304

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --verbosity normal

      - run: tree .

      - name: Publish linux-x64
        run: dotnet publish "${{ github.workspace }}/BioParallel/BioParallel.csproj" -r linux-x64 -p:PublishDir="C:/${{ github.event.repository.name }}/linux-x64" -c Release -f net7.0 -p:PublishSingleFile=true --self-contained --verbosity normal

      - name: Publish win-x64
        run: dotnet publish "${{ github.workspace }}/BioParallel/BioParallel.csproj" -r win-x64 -p:PublishDir="C:/${{ github.event.repository.name }}/win-x64" -c Release -f net7.0 -p:PublishSingleFile=true --self-contained --verbosity normal
        
      - name: Publish osx-x64
        run: dotnet publish "${{ github.workspace }}/BioParallel/BioParallel.csproj" -r osx-x64 -p:PublishDir="C:/${{ github.event.repository.name }}/osx-x64" -c Release -f net7.0 -p:PublishSingleFile=true --self-contained --verbosity normal
        
      - name: Copy License, README etc.
        run: Copy-Item * C:/${{ github.event.repository.name }} -Include LICENSE,README.md 
        
      - run: tree .
      - run: tree "C:/${{ github.event.repository.name }}"
      
      - name: Upload a Build Artifacts for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: C:/${{ github.event.repository.name }}

          retention-days: 1

  deploy:
    name: Deploy ${{ github.event.repository.name }}-${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Download a Build Artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: artifact

      - run: tree .
      
      - name: Grant permission to OSX and Linux executables and zip all releases
        run: |
          for i in */; do
            cd $i; 
            [[ -f ${{ github.event.repository.name }}-${{ inputs.tag }}/${{ github.event.repository.name }} ]] && 
            sudo chmod 777 ${{ github.event.repository.name }}-${{ inputs.tag }}/${{ github.event.repository.name }}; 
            find ../. -type f -execdir cp "{}" $i ";"
            zip -r "../${{ github.event.repository.name }}-${{ inputs.tag }}_${i%/}.zip" "."; 
            cd ..; 
          done

      - run: tree .

      - name: Release ${{ github.event.repository.name }}-${{ inputs.tag }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
          tag_name: ${{ inputs.tag }}
